### ISSUE TITLE
在mohist服务器中使用/inv与/playerinv 指令时报错且无法开启GUI

### ISSUE THREAD

**Issue by 23578951** [YXMAX/PlayerInv#1]
服务器类型：mohist
服务器版本：mohist-1.12.2-314-server
游戏版本：1.12.2

[16:53:30 INFO]: Penny_S 使用了指令: /inv
[16:53:30 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'inv' in plugin PlayerInv v1.3.70-v1.12.2 Official Version
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[SimpleCommandMap.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1617) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1456) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:91) ~[ItemStack.class:?]
        at com.playerinv.MainGUI.GUIManager.MainGUI(GUIManager.java:638) ~[?:?]
        at com.playerinv.Command.InvCommand.onCommand(InvCommand.java:105) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
        ... 15 more

**Comment by YXMAX** [comment]
加qq交流群反映插件问题 473358045
