### ISSUE TITLE
PlayerInv 插件版本 2.7.55 在处理 PlaceholderAPI 请求时遇到了null 字符串转换为整数，导致了 NumberFormatException

### ISSUE THREAD

**Issue by zrbiao** [YXMAX/PlayerInv#2]
[23:16:05 WARN]: java.lang.NumberFormatException: Cannot parse null string
[23:16:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:624)
[23:16:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:778)
[23:16:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PluginSet.getVault(PluginSet.java:870)
[23:16:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PlaceHolder.PlaceholderExpansion.onPlaceholderRequest(PlaceholderExpansion.java:46)
[23:16:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[23:16:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[23:16:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[23:16:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[23:16:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.hooks.PapiHook.parse(PapiHook.java:192)
[23:16:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$4(BukkitDataSender.java:66)
[23:16:05 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[23:16:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$5(BukkitDataSender.java:65)
[23:16:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.buildJsonBody(AbstractDataSender.java:140)
[23:16:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.run(AbstractDataSender.java:155)
[23:16:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[23:16:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[23:16:05 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[23:16:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[23:16:05 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[23:16:05 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[23:16:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[23:16:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:17:05 WARN]: java.lang.NumberFormatException: Cannot parse null string
[23:17:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:624)
[23:17:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:778)
[23:17:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PluginSet.getVault(PluginSet.java:870)
[23:17:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PlaceHolder.PlaceholderExpansion.onPlaceholderRequest(PlaceholderExpansion.java:46)
[23:17:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[23:17:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[23:17:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[23:17:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[23:17:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.hooks.PapiHook.parse(PapiHook.java:192)
[23:17:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$4(BukkitDataSender.java:66)
[23:17:05 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[23:17:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$5(BukkitDataSender.java:65)
[23:17:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.buildJsonBody(AbstractDataSender.java:140)
[23:17:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.run(AbstractDataSender.java:155)
[23:17:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[23:17:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[23:17:05 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[23:17:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[23:17:05 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[23:17:05 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[23:17:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[23:17:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:18:05 WARN]: java.lang.NumberFormatException: Cannot parse null string
[23:18:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:624)
[23:18:05 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:778)
[23:18:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PluginSet.getVault(PluginSet.java:870)
[23:18:05 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.PlaceHolder.PlaceholderExpansion.onPlaceholderRequest(PlaceholderExpansion.java:46)
[23:18:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[23:18:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[23:18:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[23:18:05 WARN]:        at PlaceholderAPI-2.11.6.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[23:18:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.hooks.PapiHook.parse(PapiHook.java:192)
[23:18:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$4(BukkitDataSender.java:66)
[23:18:05 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[23:18:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.bukkit.BukkitDataSender.lambda$registerCustomProviders$5(BukkitDataSender.java:65)
[23:18:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.buildJsonBody(AbstractDataSender.java:140)
[23:18:05 WARN]:        at Nameless-Plugin-Paper-3.4.1.jar//com.namelessmc.plugin.common.AbstractDataSender.run(AbstractDataSender.java:155)
[23:18:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[23:18:05 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[23:18:05 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[23:18:05 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[23:18:05 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[23:18:05 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[23:18:05 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[23:18:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

通义ai助手检查结果
这段日志显示了 PlayerInv 插件版本 2.7.55 在处理 PlaceholderAPI 请求时遇到了问题。具体来说，问题出现在 PluginSet.java 文件的第 870 行，该行代码试图将一个 null 字符串转换为整数，导致了 NumberFormatException。

为了解决这个问题，你需要查看 PluginSet.java 文件中第 870 行的具体代码，并确保不会尝试将 null 字符串转换为整数。
计算玩家拥有的库存数量，基于他们拥有的权限。这里的问题是在某些情况下，Placeholder_Vault_Amount.get(player) 可能返回 null，从而导致 NumberFormatException 当尝试将其转换为整数时。

        Placeholder_List.add(player.getName());
        Placeholder_Vault_Amount.put(player, String.valueOf(count));
        return count;
    } else {
        // 这里添加非空检查
        String vaultAmountStr = Placeholder_Vault_Amount.get(player);
        if (vaultAmountStr != null && !vaultAmountStr.trim().isEmpty()) {
            return Integer.parseInt(vaultAmountStr);
        } else {
            // 如果 vaultAmountStr 为空或空白，可以返回默认值或处理这种情况
            return 0; // 或者抛出异常等
        }
    }
}

**Comment by zrbiao** [comment]
顺便说一句 我并不会java 只是后台报错给ai检查出来的
希望能修复这个错误

**Comment by YXMAX** [comment]
v2.7.60 版本已修复
