### ISSUE TITLE
 PlayerInv 插件检查更新后台报错

### ISSUE THREAD

**Issue by zrbiao** [YXMAX/PlayerInv#3]
[09:27:15 WARN]: java.net.ConnectException: 连接超时
[09:27:15 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[09:27:15 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:589)
[09:27:15 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:578)
[09:27:15 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[09:27:15 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[09:27:15 WARN]:        at java.base/java.net.Socket.connect(Socket.java:751)
[09:27:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[09:27:15 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
[09:27:15 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[09:27:15 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[09:27:15 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[09:27:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[09:27:15 WARN]:        at PlayerInv-2.7.55.jar//com.playerinv.updatechecker.UpdateChecker.lambda$checkNow$5(UpdateChecker.java:336)
[09:27:15 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[09:27:15 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[09:27:15 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:27:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[09:27:15 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[09:27:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[09:27:15 WARN]: [PlayerInv] Could not check for updates.

**Comment by YXMAX** [comment]
检查更新报错是正常的 通常国内连接Github api较为困难
